spring.datasource.url=jdbc:postgresql://ep-odd-term-ac6cd2sy-pooler.sa-east-1.aws.neon.tech/neondb?sslmode=require

spring.datasource.username=neondb_owner
spring.datasource.password=npg_RK2MOZWi4lnz

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080